### ISSUE TITLE
Match significance statistics with the old method

### ISSUE THREAD

**Issue by KwatMDPhD** [KwatMDPhD/gsea.py#19] opened 2021-07-28 01:59 UTC
@ACastanza

**Comment by ACastanza** [comment] 2021-07-29 21:05
I think the issue is that it isn't generating the Normalized enrichment score so it can't properly run the FDR calculation, which, if I recall correctly, is based on the NES distribution.

**Comment by KwatME** [comment] 2021-07-30 22:38
Oh I see. I did not normalize before commuting significances.

**Comment by ACastanza** [comment] 2021-07-30 22:49
Only for the FDR though, not the NOM pValue, since the NOM pValue is only computed vs. a single gene set's null distribution it doesn't need the normalized score, whereas the FDR is computed as a global statistic it needs to first remove gene set size as a variable which using the NES accomplishes. (If I recall correctly)

**Comment by pablotamayo** [comment] 2021-07-31 18:16
Hi guys,

Now that we are revisiting this I think we should compute both the p-values and FDRs consistently using the same NES normalized-scores global null distribution so that both, p-vals and FDR, statistics always increase and become less statistically significant, as the scores decrease going down the list.  Because of the way we normalize the ES scores we are already assuming that the local null distributions converge to a global null distribution (they don't converge perfectly but well enough to make that assumption).

Kwat, if you recall, is similar to the way we do it in the "match_features_against_phenotype" in ccal.

It is better not to compute the p-vals with the un-normalized enrichment scores because the scale of the local null distributions is different (it is gene set size-dependent), and if we compute the p-val and the local null distribution for each gene set independently, then the p-values will fluctuate because of sampling variation. The problem with this is that gene sets with lower enrichment scores may attain better p-values. In addition, the FDRs cannot be defined consistently in that case.

As Anthony points out the FDRs need to be computed with a global null distribution so the proposed approach will work fine for those and be consistent as both p-val and FDRs share the same global null distribution.

--Pablo


________________________________

**Comment by ACastanza** [comment] 2021-08-03 21:48
The gene set size is a constant for each individual gene set and the pValues are determined only by the distribution for a given gene set. This is the same in both phenotype and gene set permutation mode as the gene set mode samples an equally sized random set in the permutation generation. Would computing based on NES even change the result here since it should effectively factor out of the equation?

Also, even if it does change I'm not sure it should be changed. Largely because the goal (here at least) was to replicate the behavior of the existing algorithm so, at least for running the KS test it should run the old behavior.

**Comment by pablotamayo** [comment] 2021-08-03 22:38
"The gene set size is a constant for each individual gene set and the pValues are determined only by the distribution for a given gene set."

That is a problem because you are computing p-values of different distributions (gene sets of different sizes) and then when you list the p-values next to each other, they are actually coming from different statistical tests that are not integrated. The source of the problem goes back to the KS statistic that has a dependence on the gene set size.

"Would computing based on NES even change the result here since it should effectively factor out of the equation?" Yes, but the test needs to use a global null distribution where all the NES scores of the permutations are merged.

We should try to replicate the existing approach as much as we can but also fix problems e.g. with the way the gene ranking metrics or the statistical testing was implemented.

--Pablo




________________________________

**Comment by davideby** [comment] 2021-08-03 23:30
One thing we've done in the past with the Desktop in such situations is to keep both implementations (the original problematic one along with the new fixed one) and just have a switch of some kind to toggle between them.  The new behavior would be the default but the old one would still be present for comparison and we'd just have documentation to explain why we chose to favor one over the other.

As an example, consider the "weighted" vs. "classic" modes for the Enrichment statistic parameter or the "meandiv" normalization mode.

If reviewers or users are to evaluate the new implementation against the old, they need to be able to compare them directly and side-by-side.

**Comment by ACastanza** [comment] 2021-08-05 21:15
`"Would computing based on NES even change the result here since it should effectively factor out of the equation?" Yes, but the test needs to use a global null distribution where all the NES scores of the permutations are merged.`

But that's not what the NOM pValue does. The NOM pValue only calculates a significance statistic for a single gene set given it's own individual null distribution. The FDR is what is using/should be using the global distribution, and thus needs to be normalized to gene set size (what the desktop currently does, and the fix that needs to be made here).

Maybe I'm misunderstanding what you're saying here.

**Comment by pablotamayo** [comment] 2021-08-05 23:56
What I'm saying is that it is better to replace the nominal p-value with the adjusted p-value that comes from the same global null distribution as the FDRs. If we think people may not like that because it will make their favorite gene sets look less significant (which they probably are) we could also keep the nominal p-value and add an adjusted one (and maybe get rid of the FWER one).

--Pablo

________________________________

**Comment by KwatME** [comment] 2021-09-13 22:02
ETA few days; @pablotamayo I messaged you to go over this.

**Closed** 2021-11-26 06:24 UTC
